package com.gbc.gui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Settings.java
 *
 * Created on Nov 26, 2011, 5:01:52 PM
 */

import com.gbc.bean.RGBBean;
import com.gbc.bean.SettingsBean;
import com.gbc.util.AppConstants;
import com.gbc.util.Utilities;
import java.awt.Frame;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Administrator
 */
public class ColorSettingsDialog extends javax.swing.JDialog {

    /** Creates new form Settings */
    SettingsBean settingsBean = null;

    ColorSettingsDialog(Frame lid, boolean modal, SettingsBean settingsBean) {
        super (lid,modal);
        this.settingsBean = settingsBean;
        AppConstants.isFingerTipOn = false;
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().createImage(getClass().getResource("/icon/colour_22.png")));
        setLocationRelativeTo(null);
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ColorSettingsDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ColorSettingsDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ColorSettingsDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ColorSettingsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
            SwingUtilities.updateComponentTreeUI(this);
        loadValues("Red");
        this.pack();
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        redMaxSlider = new javax.swing.JSlider();
        greenMaxSlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        blueMaxSlider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        redMaxLabel = new javax.swing.JLabel();
        greenMaxLabel = new javax.swing.JLabel();
        blueMaxLabel = new javax.swing.JLabel();
        canceclButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        redMinSlider = new javax.swing.JSlider();
        greenMinSlider = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        blueMinSlider = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        redMinLabel = new javax.swing.JLabel();
        greenMinLabel = new javax.swing.JLabel();
        blueMinLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Maximum"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel1.setText("Red");

        redMaxSlider.setMaximum(255);
        redMaxSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                redMaxSliderStateChanged(evt);
            }
        });

        greenMaxSlider.setMaximum(255);
        greenMaxSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                greenMaxSliderStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel2.setText("Green");

        blueMaxSlider.setMaximum(255);
        blueMaxSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                blueMaxSliderStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel3.setText("Blue");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel4.setText("Red");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel5.setText("Green");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel6.setText("Blue");

        redMaxLabel.setText("1");

        greenMaxLabel.setText("2");

        blueMaxLabel.setText("3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blueMaxSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greenMaxSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redMaxSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(redMaxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blueMaxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(greenMaxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(redMaxLabel))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(redMaxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(greenMaxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(greenMaxLabel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(blueMaxLabel))
                    .addComponent(jLabel3)
                    .addComponent(blueMaxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        canceclButton.setText("Cancel");
        canceclButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceclButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Minimum"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel7.setText("Red");

        redMinSlider.setMaximum(255);
        redMinSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                redMinSliderStateChanged(evt);
            }
        });

        greenMinSlider.setMaximum(255);
        greenMinSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                greenMinSliderStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel8.setText("Green");

        blueMinSlider.setMaximum(255);
        blueMinSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                blueMinSliderStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel9.setText("Blue");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel10.setText("Red");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel11.setText("Green");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel12.setText("Blue");

        redMinLabel.setText("4");

        greenMinLabel.setText("5");

        blueMinLabel.setText("5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blueMinSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greenMinSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redMinSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(redMinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blueMinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(greenMinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                .addGap(12, 12, 12)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(redMinLabel))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(redMinSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(greenMinSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(greenMinLabel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(blueMinLabel))
                    .addComponent(jLabel9)
                    .addComponent(blueMinSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel13.setText("Color");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Red", "Green", "Blue" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canceclButton)
                .addGap(22, 22, 22))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {canceclButton, jButton2, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canceclButton)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redMaxSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_redMaxSliderStateChanged
        // TODO add your handling code here:
        // System.out.println("State changed");
        redMaxLabel.setText("" + redMaxSlider.getValue());
    }//GEN-LAST:event_redMaxSliderStateChanged

    private void greenMaxSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_greenMaxSliderStateChanged
        // TODO add your handling code here:
        greenMaxLabel.setText("" + greenMaxSlider.getValue());
    }//GEN-LAST:event_greenMaxSliderStateChanged

    private void blueMaxSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_blueMaxSliderStateChanged
        // TODO add your handling code here:
        blueMaxLabel.setText("" + blueMaxSlider.getValue());
    }//GEN-LAST:event_blueMaxSliderStateChanged

    private void redMinSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_redMinSliderStateChanged
        // TODO add your handling code here:
        redMinLabel.setText("" + redMinSlider.getValue());
    }//GEN-LAST:event_redMinSliderStateChanged

    private void greenMinSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_greenMinSliderStateChanged
        // TODO add your handling code here:
        greenMinLabel.setText("" + greenMinSlider.getValue());
    }//GEN-LAST:event_greenMinSliderStateChanged

    private void blueMinSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_blueMinSliderStateChanged
        // TODO add your handling code here:
        blueMinLabel.setText("" + blueMinSlider.getValue());
    }//GEN-LAST:event_blueMinSliderStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Utilities.serializeSettingsBean();
        this.setVisible(false);
        loadValues();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        //  System.out.println("State changed");
        loadValues((String) jComboBox1.getSelectedItem());
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        RGBBean colorBean = new RGBBean();
        colorBean.setMaxRed(redMaxSlider.getValue());
        colorBean.setMaxGreen(greenMaxSlider.getValue());
        colorBean.setMaxBlue(blueMaxSlider.getValue());

        colorBean.setMinRed(redMinSlider.getValue());
        colorBean.setMinGreen(greenMinSlider.getValue());
        colorBean.setMinBlue(blueMinSlider.getValue());

        String selectedColor = (String) jComboBox1.getSelectedItem();
        if (selectedColor.equalsIgnoreCase("Red")) {
            AppConstants.settingsBean.setRedColor(colorBean);
        }
        if (selectedColor.equalsIgnoreCase("Green")) {
            AppConstants.settingsBean.setGreenColor(colorBean);
        }
        if (selectedColor.equalsIgnoreCase("Blue")) {
            AppConstants.settingsBean.setBlueColor(colorBean);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

private void canceclButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceclButtonActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_canceclButtonActionPerformed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// TODO add your handling code here:
    AppConstants.isFingerTipOn = true;
}//GEN-LAST:event_formWindowClosing
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blueMaxLabel;
    private javax.swing.JSlider blueMaxSlider;
    private javax.swing.JLabel blueMinLabel;
    private javax.swing.JSlider blueMinSlider;
    private javax.swing.JButton canceclButton;
    private javax.swing.JLabel greenMaxLabel;
    private javax.swing.JSlider greenMaxSlider;
    private javax.swing.JLabel greenMinLabel;
    private javax.swing.JSlider greenMinSlider;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel redMaxLabel;
    private javax.swing.JSlider redMaxSlider;
    private javax.swing.JLabel redMinLabel;
    private javax.swing.JSlider redMinSlider;
    // End of variables declaration//GEN-END:variables

    private void loadValues(String color) {
        RGBBean colorBean = null;
        if (color.equalsIgnoreCase("Red")) {
            colorBean = settingsBean.getRedColor();
        }
        if (color.equalsIgnoreCase("Green")) {
            colorBean = settingsBean.getGreenColor();
        }
        if (color.equalsIgnoreCase("Blue")) {
            colorBean = settingsBean.getBlueColor();
        }
        redMaxSlider.setValue(colorBean.getMaxRed());
        greenMaxSlider.setValue(colorBean.getMaxGreen());
        blueMaxSlider.setValue(colorBean.getMaxBlue());

        redMinSlider.setValue(colorBean.getMinRed());
        greenMinSlider.setValue(colorBean.getMinGreen());
        blueMinSlider.setValue(colorBean.getMinBlue());

        redMaxLabel.setText("" + colorBean.getMaxRed());
        greenMaxLabel.setText("" + colorBean.getMaxGreen());
        blueMaxLabel.setText("" + colorBean.getMaxBlue());

        redMinLabel.setText("" + colorBean.getMinRed());
        greenMinLabel.setText("" + colorBean.getMinGreen());
        blueMinLabel.setText("" + colorBean.getMinBlue());
    }

     private void loadValues() {
        AppConstants.RED_COMPONENT_OF_RED_MAX = AppConstants.settingsBean.getRedColor().getMaxRed();
        AppConstants.GREEN_COMPONENT_OF_RED_MAX = AppConstants.settingsBean.getRedColor().getMaxGreen();
        AppConstants.BLUE_COMPONENT_OF_RED_MAX = AppConstants.settingsBean.getRedColor().getMaxBlue();


        AppConstants.RED_COMPONENT_OF_GREEN_MAX = AppConstants.settingsBean.getGreenColor().getMaxRed();
        AppConstants.GREEN_COMPONENT_OF_GREEN_MAX = AppConstants.settingsBean.getGreenColor().getMaxGreen();
        AppConstants.BLUE_COMPONENT_OF_GREEN_MAX = AppConstants.settingsBean.getGreenColor().getMaxBlue();

        AppConstants.RED_COMPONENT_OF_BLUE_MAX = AppConstants.settingsBean.getBlueColor().getMaxRed();
        AppConstants.GREEN_COMPONENT_OF_BLUE_MAX = AppConstants.settingsBean.getBlueColor().getMaxGreen();
        AppConstants.BLUE_COMPONENT_OF_BLUE_MAX = AppConstants.settingsBean.getBlueColor().getMaxBlue();


        AppConstants.RED_COMPONENT_OF_RED_MIN = AppConstants.settingsBean.getRedColor().getMinRed();
        AppConstants.GREEN_COMPONENT_OF_RED_MIN = AppConstants.settingsBean.getRedColor().getMinGreen();
        AppConstants.BLUE_COMPONENT_OF_RED_MIN = AppConstants.settingsBean.getRedColor().getMinBlue();


        AppConstants.RED_COMPONENT_OF_GREEN_MIN = AppConstants.settingsBean.getGreenColor().getMinRed();
        AppConstants.GREEN_COMPONENT_OF_GREEN_MIN = AppConstants.settingsBean.getGreenColor().getMinGreen();
        AppConstants.BLUE_COMPONENT_OF_GREEN_MIN = AppConstants.settingsBean.getGreenColor().getMinBlue();

        AppConstants.RED_COMPONENT_OF_BLUE_MIN = AppConstants.settingsBean.getBlueColor().getMinRed();
        AppConstants.GREEN_COMPONENT_OF_BLUE_MIN = AppConstants.settingsBean.getBlueColor().getMinGreen();
        AppConstants.BLUE_COMPONENT_OF_BLUE_MIN = AppConstants.settingsBean.getBlueColor().getMinBlue();

    }
}
